### ISSUE TITLE
页面很像，但是也能发现不同，很强

### ISSUE THREAD

**Issue by jcss0610** [sun589/QQ_Skey#1]
但是我用小号试了试，好像并不能准确获取QQ密码，可惜了，我还想用这个报复骗我钱的呢

**Comment by sun589** [comment]
这个实际就是我写着玩的,没想到还真有人来看...
这个是skey,密码是存在tx数据库的,这个项目现在也懒得更新了(等我有空再来看看ba:)...

**Comment by sun589** [comment]
skey只能实现发送公告一类内容,如果想更强的可以花点¥去找技术大牛
比如强进空间,钱包,群管理和植入木马自动获取qq客户端skey:)

**Comment by sun589** [comment]
所以你还在吗,我有把我上一句话说的强进空间等全部做出来了,需要的话就去release下,如果喜欢记得给我打个star:)

**Comment by jcss0610** [comment]
好强大，stars了，感谢您还记得我，很感动。
